import ProjectDescription

let workspace = Workspace(
  name: "Gabbangzip",
  projects: [
    "Projects/App",
    "Projects/Core",
    "Projects/DesignSystem",
    "Projects/Features/Scene",
    "Projects/Features/Coordinator",
  ],
  schemes: [
    .scheme(
      name: "Prod-Gabbangzip",
      buildAction: .buildAction(targets: [.project(path: "./Projects/App", target: "Prod-Gabbangzip")]),
      runAction: .runAction(
        configuration: .release,
        arguments: .arguments(environmentVariables: ["IDEPreferLogStreaming": "YES"])
      ),
      archiveAction: .archiveAction(configuration: .release),
      profileAction: .profileAction(configuration: .release),
      analyzeAction: .analyzeAction(configuration: .release)
    ),
    .scheme(
      name: "Dev-Gabbangzip",
      buildAction: .buildAction(targets: [.project(path: "./Projects/App", target: "Dev-Gabbangzip")]),
      runAction: .runAction(
        configuration: .debug,
        arguments: .arguments(environmentVariables: ["IDEPreferLogStreaming": "YES"])
      ),
      archiveAction: .archiveAction(configuration: .debug),
      profileAction: .profileAction(configuration: .debug),
      analyzeAction: .analyzeAction(configuration: .debug)
    ),
    .scheme(
      name: "DesignSystem",
      buildAction: .buildAction(targets: [
        .project(path: "./Projects/DesignSystem", target: "DesignSystem")
      ]),
      runAction: .runAction(
        configuration: .debug
      ),
      archiveAction: .archiveAction(configuration: .debug),
      profileAction: .profileAction(configuration: .debug),
      analyzeAction: .analyzeAction(configuration: .debug)
    )
  ],
  generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
