# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

update_fastlane()

default_platform(:ios)

platform :ios do 
  desc "Push a new beta build to TestFlight"
  lane :beta do |options|
    new_version_number = options[:new_version_number]
    new_build_number = options[:new_build_number]
    set_build_info(new_version_number, new_build_number)

    update_and_build_app("Prod")
    upload_to_testflight(
      app_identifier: "com.mashup.gabbangzip",
      api_key_path: "fastlane/key.json",
      skip_waiting_for_build_processing: true
    )
    download_dsyms(
      app_identifier: "com.mashup.gabbangzip",
      output_directory: "./Projects/App/Outputs/Archives/PROD"
    )

    update_and_build_app("Dev")
    upload_to_testflight(
      app_identifier: "com.mashup.gabbangzip-dev",
      api_key_path: "fastlane/key.json",
      skip_waiting_for_build_processing: true
    )
    download_dsyms(
      app_identifier: "com.mashup.gabbangzip-dev",
      output_directory: "./Projects/App/Outputs/Archives/DEV"
    )

    create_tag(new_version_number, new_build_number)
  end

  desc "Push a new production build to TestFlight"
  lane :prod do |options|
    new_version_number = options[:new_version_number]
    new_build_number = options[:new_build_number]
    set_build_info(new_version_number, new_build_number)

    update_and_build_app("Prod")
    upload_to_testflight(
      app_identifier: "com.mashup.gabbangzip",
      api_key_path: "fastlane/key.json",
      skip_waiting_for_build_processing: true
    )

    create_tag(new_version_number, new_build_number)
  end

  desc "Push a new dev build to TestFlight"
  lane :dev do |options|
    new_version_number = options[:new_version_number]
    new_build_number = options[:new_build_number]
    create_tag = options[:create_tag]
    set_build_info(new_version_number, new_build_number)

    update_and_build_app("Dev")
    upload_to_testflight(
      app_identifier: "com.mashup.gabbangzip-dev",
      api_key_path: "fastlane/key.json",
      skip_waiting_for_build_processing: true
    )
    
    if create_tag 
      create_tag(new_version_number, new_build_number)
    end
  end
end

def set_build_info(new_version_number, new_build_number)
  marketing_version = get_xcconfig_value("MARKETING_VERSION", '../Projects/App/xcconfigs/Gabbangzip.shared.xcconfig')
  build_number = get_xcconfig_value("CURRENT_PROJECT_VERSION", '../Projects/App/xcconfigs/Gabbangzip.shared.xcconfig')

  if new_version_number.nil? || new_version_number.empty?
    new_version_number = marketing_version
  end

  if new_build_number.nil? || new_build_number.empty?
    new_build_number = build_number
  end

  set_xcconfig_value("MARKETING_VERSION", new_version_number)
  increment_build_number(
    xcodeproj: './Projects/App/App.xcodeproj',
    build_number: new_build_number
  )
end

def create_tag(new_version_number, new_build_number)
  tag_name = "#{new_version_number}-#{new_build_number}"
  
  system( `git tag #{tag_name} && git push -u origin "#{tag_name}"` )
end

def get_xcconfig_value(targetKey, xcconfigs_file_path)
  configs = {}
 
  # read configs
  File.open(xcconfigs_file_path, "r").each_line do |line|
    value = line.split("=")
    configs[value[0]] = value[1].strip
  end

  return configs[targetKey]
end

def set_xcconfig_value(targetKey, targetValue, xcconfigs_file_path = '../Projects/App/xcconfigs/Gabbangzip.shared.xcconfig')
  configs = {}
 
  # read configs
  File.open(xcconfigs_file_path, "r").each_line do |line|
    value = line.split("=")
    configs[value[0]] = value[1].strip
  end

  # register configs
  configs[targetKey] = targetValue

  # write configs
  File.open(xcconfigs_file_path, 'w') do |out_file|
    configs.each do |key, value|
      out_file.puts "#{key}=#{value}"
    end
  end
end

def update_and_build_app(scheme = "")
  case scheme
  when "Prod"
    match(
      type: "appstore",
      app_identifier: "com.mashup.gabbangzip",
      force_for_new_devices: true,
      readonly: true
    )
    build_app(
      workspace: "Gabbangzip.xcworkspace",
      output_directory: "./Projects/App/Outputs/Archives/PROD",
      scheme: "#{scheme}-Gabbangzip",
      xcargs: "-allowProvisioningUpdates"
    )
  when "Dev"
    match(
      type: "appstore",
      app_identifier: "com.mashup.gabbangzip-dev",
      force_for_new_devices: true,
      readonly: true
    )
    build_app(
      workspace: "Gabbangzip.xcworkspace",
      output_directory: "./Projects/App/Outputs/Archives/DEV",
      scheme: "#{scheme}-Gabbangzip",
      xcargs: "-allowProvisioningUpdates"
    )
  else
    throw
  end
end